### ISSUE TITLE
2019-04-22 OKC Networking Fair

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#103]
Let me know if you're interested in helping us organize a networking fair in Oklahoma City! It will be very similar to the Free Code Camp OKC meet and greet events/job fairs but for all Techlahoma members in the OKC metro.

https://youtu.be/sALtyh5l5ag 

Committee: Membership
Contact: Kimberly Collins
Slack: #techlahoma-volunteers channel

**Comment by gtxtreme21** [comment]
Hi Kimberly, do you need physical help setting up the venue ( tables | chairs )?
I'm available to help out with any physical or coding tasks needed.
Regards,
Gary Tipton

**Comment by kacollins** [comment]
We'd love some help with setting up the tables and chairs at the venue before we start! The hardest part will be figuring out how to arrange the tables for the two different sponsorship levels. The premium booths are bigger and need to be near power outlets.
