### ISSUE TITLE
Unexported Twitch Highlights

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#11]
[Volunteers](https://github.com/techlahoma/help-wanted/issues/29) export highlights from Techlahoma's [Twitch channel](https://www.twitch.tv/techlahoma) to Techlahoma's [YouTube channel](https://www.youtube.com/c/techlahoma). It can be difficult to find which highlights need to be exported. 

We'd love to have a webpage that displays a list of Techlahoma's Twitch highlights that have not been exported to YouTube! The hard part will be matching the Twitch highlights to the Youtube videos, because the titles aren't always in the same format.

Committee: Broadcasting
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by Jason9199** [comment]
I don't know if this is possible if you can't count on the format of the YouTube videos being consistent. ☹️

**Comment by kacollins** [comment]
I think it will be hard, but not impossible. The first step will be to show exact matches. The next step is probably to match on the parts being the same but in a different order or with different punctuation.
