### ISSUE TITLE
YouTube Tags/Keywords

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#110]
Display a list of the videos on Techlahoma's [YouTube channel](https://youtube.com/c/techlahoma) that have the fewest keywords. This will help volunteers add keywords to the videos that need them, so people will find the videos on YouTube.

Committee: Content Creation
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by Archyver** [comment]
Not sure how feasible it is, but could this be added to @brickbeard 's twitch highlight tool. Seeing a list of keywords/tags might inspire more tags for future videos.

**Comment by kacollins** [comment]
I agree! I wouldn't be surprised if this tool ends up incorporating a lot of the content creation items on the help wanted board.
