### ISSUE TITLE
Help or advice on writing and distributing press releases

### ISSUE THREAD

**Issue by kendallcorner** [techlahoma/help-wanted#13]

**Comment by groovecoder** [comment]
Do you have contact info for Jarrel Wade?

**Comment by kendallcorner** [comment]
Nope. That was him, Friday, right?

--
Kendall Werts
twitter <https://twitter.com/kendallcorner>|linkedin
<http://www.linkedin.com/in/kendallwerts>
918-640-1377

**Comment by carmalou** [comment]
@kendallcorner or @groovecoder can this issue be closed?

**Comment by groovecoder** [comment]
I just sent an email to Jarrel about it. Let's call this closed.
