### ISSUE TITLE
Help Wanted Issues

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#22]
Could this app pull in "help wanted" issues from other Techlahoma repos? For example: https://github.com/techlahoma/Event-Intro/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by carmalou** [comment]
I think it would be best if UGLs or comm chairs came to this repo and opened the issues here. That's what the readme says. I don't see any reason we couldn't open issues here for other repos so long as we specify which repo && contact person && the label is indicative of which UGL or comm.

**Comment by kacollins** [comment]
My concern is keeping the issues in sync between the two repos (this one and the one referenced), but maybe we could have a general issue here that points to the issue list in another repo.
