### ISSUE TITLE
SheCodes Django OKC Workshop Volunteers and Coaches

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#25]
The workshops committee is looking for volunteers and coaches for a Django workshop for women in Oklahoma City in August.

Committee: Workshops
Contact: Kimberly Collins
Slack: kimberlycollins

**Comment by groovecoder** [comment]
When is it? I'll try to coach.

**Comment by kacollins** [comment]
Awesome! We're hoping to get the date set any day now, but we're planning on August 3-4.

**Comment by energydev** [comment]
Are you looking for volunteers and coaches the days of the event or possibly also some volunteers to help with event planning?

**Comment by kacollins** [comment]
We will definitely need volunteers and coaches on the days of the event! Mark your calendars for the 5:30-7:30 on August 3 and 9-5 on August 4, but those dates haven't been confirmed yet.

**Comment by kacollins** [comment]
Here's the link to sign up to coach: https://goo.gl/forms/J2PegbGRArd3RF1S2

**Comment by kacollins** [comment]
We're also looking for people to give lightning talks during the workshop to introduce topics in the [tutorial](https://tutorial.djangogirls.org/en), including Python, Django, Git, GitHub, and Python Anywhere.

**Comment by kacollins** [comment]
We got some great [coaches](https://kacollins.github.io/django-okc/index.html#coaches) and volunteers to sign up!
