### ISSUE TITLE
Announcement Slide Automation

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#27]
Free Code Camp OKC likes to share about user group meetups for the upcoming week during the announcements. It would be great if those slides could be created programmatically using the Meetup API.

User Group: Free Code Camp OKC
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by claytonflesher** [comment]
Hey Kimberley. I made a [1.0 version](https://techlahoma-meetups.herokuapp.com) of it this evening.

Here's the [codebase](https://github.com/claytonflesher/techlahoma_slides)

**Comment by kacollins** [comment]
This is fantastic! Thank you!

**Comment by claytonflesher** [comment]
I put out a new version with the updates we discussed this morning. Let me know if you need any other changes.

**Comment by Jason9199** [comment]
Should this be closed now?

**Comment by kacollins** [comment]
Yep, I guess so. Thanks, guys!
