### ISSUE TITLE
YouTube Descriptions

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#30]
Display a list of the videos on Techlahoma's [YouTube channel](https://youtube.com/c/techlahoma) that have the fewest keywords and a list of the ones with the shortest descriptions. Adding details to the videos will help people find them and learn more!

Committee: Broadcasting
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by bshambaugh** [comment]
Start from: https://www.youtube.com/channel/UCnLf0pfqIpSfKuPZ0e9iiNQ

**Comment by BlakeGerard** [comment]
I have a local solution for description length using YouTube Data API. The API doesn't provide a way to access keywords so that would have to be done through scraping.
