### ISSUE TITLE
A/V Documentation

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#32]
Put documentation for A/V, Twitch, and YouTube processes into the [Techlahoma wiki](http://www.techlahoma.us):
https://github.com/techlahoma/techlahoma/wiki/How-to-get-a-streamed-video-from-Twitch-to-Youtube
https://github.com/techlahoma/user-groups/wiki/Streaming-Instructions

Committee: OKC Broadcasting
Contact: Kimberly Collins
Slack: kimberlycollins
Email: kcollins at techlahoma dot org

**Comment by Avasond** [comment]
For people on the broadcasting committee who need troubleshooting help, I have a notepad document on the toolbar of the stream PC that has my contact info and a few fixes for common troubleshooting problems. I plan on porting this list, but it's still under construction at the moment.

**Comment by kacollins** [comment]
There's still work to be done on this, but we've made a lot of progress. Thanks for the pr's, @alexadriaanse!
