### ISSUE TITLE
Member Newsletter

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#34]
The user group committee is starting a newsletter for Techlahoma members and could use some volunteers to help out!

Committee: User Groups
Contact: Kimberly Collins
Slack: kimberlycollins, [#member-newsletter](https://techlahoma.slack.com/messages/member-newsletter), [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by groovecoder** [comment]
Count me in. I'll work with @Avasond to see how she's bootstrapped this in the past, and I'll work with you and the rest of the teams to fill up with content.

**Comment by kacollins** [comment]
Join the #member-newsletter channel in Slack if you're interested in helping out!

**Comment by LoveDesigning** [comment]
I would like to help. What do you need to know to contribute?

**Comment by Avasond** [comment]
Passing it off to the Newsletter Committee now. We can duplicate it and make a UGL-specific newsletter, too. Just make a UGL announcement board and change the URLs to the correct feed.

**Comment by kacollins** [comment]
We could use help with creating content!

Examples:
https://www.techlahoma.org/announcements
https://www.techlahoma.org/news

**Comment by kacollins** [comment]
@LoveDesigning, we'd love to get some help with this! We need 2-4 sentence paragraphs to include in the announcements section of the newsletter. See the [Announcements](https://www.techlahoma.org/announcements) page for examples and the [News](https://www.techlahoma.org/news) page for possible content and more examples.

The  [#member-newsletter](https://techlahoma.slack.com/messages/member-newsletter) channel in [Slack](http://slack.techlahoma.org) is the best place to post and discuss these!

**Comment by kacollins** [comment]
We are going to discontinue the newsletter until we have more people helping with it.
