### ISSUE TITLE
Twitch Prime Explanation

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#35]
People don't understand how Twitch Prime works or that it gives $5 to Techlahoma per person per month. Create an explanation and step-by step instructions for how to sign up for Twitch Prime and subscribe to Techlahoma's Twitch channel each month. Maybe a series of screenshots or even a video!

Committee: OKC Broadcasting
Contact: Kimberly Collins
Slack: kimberlycollins

**Comment by Avasond** [comment]
https://twitch.amazon.com/prime is the address where you can connect your account.

**Comment by kacollins** [comment]
Here are some detailed steps, thanks to @cotterjd!

- Go to https://twitch.amazon.com/prime
- In the bottom right corner, there's a section for "Already an Amazon Prime member?"
![image](https://user-images.githubusercontent.com/15042297/42103173-e5a23c84-7b8d-11e8-90f5-e94b77a4c08d.png)
- Click the "connect your Twitch account" link
- Click "Confirm" on the confirmation page to connect your accounts
- Go to https://www.twitch.tv/techlahoma and refresh the page
- Click "Subscribe" and it will have the free option

**Comment by kacollins** [comment]
We need a post about how to do this on the [Announcements](https://www.techlahoma.org/announcements) page!

**Comment by kacollins** [comment]
Ryan Johnson provided screenshots for the updated Twitch subscription process! https://www.techlahoma.org/announcements/2018/7/23/subscribe-to-techlahomas-twitch-channel
