### ISSUE TITLE
User Group Documentation

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#39]
Move documentation for user group leaders from the [user-groups wiki](https://github.com/techlahoma/user-groups/wiki) to the [user-group-docs](https://github.com/techlahoma/user-group-docs) repo. Maybe also add a list of frequently asked questions. Ideally, user group leaders would post their questions as GitHub issues in that repo.

Committee: User Groups
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by LoveDesigning** [comment]
I would like to help, but what would you need to know to do this?

**Comment by kacollins** [comment]
We'd love to get your help, @LoveDesigning! It turns out that we're not quite ready to transfer the documentation over, but I'll let you know when we are!

**Comment by kacollins** [comment]
We'll reopen this issue when it's ready for work. Thanks!

**Comment by kacollins** [comment]
We're going to be putting the documentation in markdown files in the https://github.com/techlahoma/how-to-usergroups GitHub repository.

**Comment by kacollins** [comment]
The best way to start would probably be to move the relevant pages from the user-groups wiki to the user-group-docs repo. This is one of the things we'll be doing at the [work day on January 5](https://goo.gl/forms/UutW9qXW048nhf072)!

**Comment by kacollins** [comment]
We had lots of help getting this done today! Thanks to @carmalou @DevinClark @austinwk @mmattice @nexocentric @rkjohns
