### ISSUE TITLE
FCCOKC Organizer

### ISSUE THREAD

**Issue by dashcraft** [techlahoma/help-wanted#40]
I will be leaving Free Code Camp OKC around august
and they will be needing a replacement to carry on my general
duties and obligations. Time frame is negotiable as i don't
want to leave free code camp until replacement is found,
but suggestions and interested persons should contact me directly for
more information.

Ideal candidate would need to perform the following duties:
Contact Local Businesses for job fair
Organize and plan meetups
Organize and plan speakers/topics
Organize and plan job fair
Periodically assist with reading the event Intro
Periodically assist with streaming events
Be present in the community as a point of contact for the group

Contact: Daniel Ashcraft
Slack Username: @dashcraft

**Comment by kacollins** [comment]
Thanks to @CarsonMcKinstry for stepping up to lead the group! If anyone else is interested in helping out, we can definitely use more volunteers!
