### ISSUE TITLE
Free Code Camp OKC Business Cards

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#46]
The leaders of Free Code Camp OKC would love to have business cards to give people when we tell them about the group! The design should include the URL for the [group website](http://www.fccokc.com/) and a little bit of information about the meetups. They're on Sunday afternoons at StarSpace46: https://www.meetup.com/FreeCodeCampOKC/

User Group: Free Code Camp OKC
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by nolawill** [comment]
Any assets, copy, guidelines already in place to work off of (beyond the initial comment above)? Or could someone take full creative license with this?

**Comment by kacollins** [comment]
Yes! Thanks for asking. We have [assets for Free Code Camp OKC](https://github.com/techlahoma/user-groups/tree/master/sponsored/Free-Code-Camp-OKC) and a [style guide from Free Code Camp](https://design-style-guide.freecodecamp.org/).

**Comment by kacollins** [comment]
Great job, @nolawill! Thank you!
