### ISSUE TITLE
SheCodes Django OKC Workshop Shirts

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#54]
We need to design and order shirts for the volunteers and coaches for the SheCodes Django OKC Workshop.

Committee: Workshops
Contact: Kimberly Collins
Slack: kimberlycollins

**Comment by Avasond** [comment]
ding ding here's the thing

![djangoworkshop](https://user-images.githubusercontent.com/25041165/42794190-2a712934-8943-11e8-91a5-a0eaf1f12189.png)

**Comment by kacollins** [comment]
Thank you, @Avasond! Great job!
