### ISSUE TITLE
Missing Issues

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#56]
Not all issues are being displayed on the help wanted board website. 

Examples:
https://github.com/techlahoma/help-wanted/issues/23
https://github.com/techlahoma/help-wanted/issues/21
https://github.com/techlahoma/help-wanted/issues/11
https://github.com/techlahoma/help-wanted/issues/10

Is there a limit to the number of issues that can be displayed?

**Comment by carmalou** [comment]
I'll take a look
