### ISSUE TITLE
figure out some styling for this app

### ISSUE THREAD

**Issue by carmalou** [techlahoma/help-wanted#6]
maybe bootstrap? idk

**Comment by nolawill** [comment]
There's also Material, Foundation, and many more. If you just want something to get up and running  with.

**Comment by nolawill** [comment]
@carmalou Ive been playing with this if you want to assign to me?

**Comment by carmalou** [comment]
@nolawill I don't seem to be able to assign you. are you able to assign yourself?

**Comment by carmalou** [comment]
this was addressed in #14
