### ISSUE TITLE
Techlahoma Business Cards

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#63]
Techlahoma business cards would be awesome to have at our various event centers to hand out to people who are interested. They could be double-sided, with one side stating our mission and having the URL techlahoma.org/get-involved , and the other side asking for support and having the URL donate.techlahoma.org 

We would print them on nice stationary on heavyweight paper to make them stick out a bit more

Contact: Vance Lucas
Slack: vlucas, [#tf_designcom](https://techlahoma.slack.com/messages/tf_designcom)

**Comment by nolawill** [comment]
Assign this to me please?

**Comment by kacollins** [comment]
Done. Thank you!

**Comment by kacollins** [comment]
Thanks again, @nolawill!
