### ISSUE TITLE
Invalid Meetup Links

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#71]
We use Google calendars for automating announcements about meetups, and they often have invalid Meetup links. I believe this happens when the meetup event is deleted. It would be great to have a list of these!

OKC User Group Calendar: https://calendar.google.com/calendar/embed?src=i1i4ar18igevhfc1vpi7g40vq8%40group.calendar.google.com&ctz=America%2FChicago
Tulsa Area User Group Calendar: https://calendar.google.com/calendar/embed?src=0k88ef5m94eol79rh7aaril148%40group.calendar.google.com&ctz=America%2FChicago

Committee: User Groups
Contact: Kimberly Collins
Slack: kimberlycollins, [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by BlakeGerard** [comment]
Requested Output:

2018-09-10 Tulsa Data Science - deleted
2018-12-24 Techogee - cancelled

**Comment by AudreySchmook** [comment]
I tested all event links through Nov. 19. They all work.
