### ISSUE TITLE
Free Code Camp OKC Facebook Posts

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#74]
Free Code Camp OKC could use some volunteers to help with posting reminders to our [Facebook group](https://www.facebook.com/groups/free.code.camp.oklahoma.city) page.

User Group: Free Code Camp OKC
Contact: Kimberly Collins
Slack: kimberlycollins, [#freecodecamp](https://techlahoma.slack.com/messages/freecodecamp)
Email: kcollins at techlahoma dot org

**Comment by vkdvamshi** [comment]
HI Kim, 

Can you please add some more details as what needs to be acheieved.

Thanks,
vkd

**Comment by kacollins** [comment]
This would be posting a reminder on the day of each meetup, and a few days in advance, so that everyone in the group knows when and where the meetups are and what they will cover. It might be possible to automate this, but I was imagining that the posts would be manual. I've been doing this and would like to hand it off to one or more people.

**Comment by carmalou** [comment]
There's no need to write code for this, as buffer offers a queue functionality.

**Comment by kacollins** [comment]
The problem is that someone's personal Facebook account is required for Buffer, and I'd rather not use mine.

**Comment by carmalou** [comment]
Yes, but that's because of the way Facebook sets up pages, so I don't think coding something custom is really going to solve that problem.

**Comment by carmalou** [comment]
Basically I'm in agreement that it should be a manual thing if we don't want to use Buffer.

**Comment by kacollins** [comment]
@CarsonMcKinstry has agreed to do this!

**Comment by CarsonMcKinstry** [comment]
Working on getting the buffer account password form @dashcraft right now. I'll update once everything's set up. 

Should we go ahead and change the account to use the freecodecampokc@gmail.com email account?

**Comment by kacollins** [comment]
Please! Thank you!
