### ISSUE TITLE
Donation Announcement

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#77]
We need text for an announcement about the membership drive, with a link to the [donation page](https://www.techlahoma.org/donate).

Contact: Kimberly Collins
Slack: kimberlycollins, [#member-newsletter](https://techlahoma.slack.com/messages/member-newsletter), [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by AudreySchmook** [comment]
I'd like to help with this!
