### ISSUE TITLE
ThunderPlains Announcement

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#78]
We need text for an announcement about ThunderPlains tickets, with a link to the [ticket page](https://ti.to/techlahoma/thunderplains-2018).

Contact: Kimberly Collins
Slack: kimberlycollins, [#member-newsletter](https://techlahoma.slack.com/messages/member-newsletter), [#techlahoma-volunteers](https://techlahoma.slack.com/messages/techlahoma-volunteers)
Email: kcollins at techlahoma dot org

**Comment by DevinClark** [comment]
Draft that we should use if there is no feedback.
> ThunderPlains Developer Conference 2018 is a great place to learn new tech and also meet people from your community! Get your ticket and we'll see YOU at the Hallway Track at ThunderPlains! Tickets are available at http://thunderplainsconf.com/.

**Comment by kacollins** [comment]
I like it! Especially the part about the hallway track. I'll go ahead and get this ready for Monday's newsletter. Thanks!

**Comment by kacollins** [comment]
There wasn't any feedback, so the text above will be in today's newsletter. Thanks, @DevinClark!
