### ISSUE TITLE
Failed Transaction Notifications

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#81]
We should be notifying donors of failed transactions.
https://stripe.com/docs/recipes/sending-emails-for-failed-payments

**Comment by kacollins** [comment]
Other possible solutions:
https://stunning.co/
https://churnbuster.io/

**Comment by carmalou** [comment]
those are still going to require connection to the stripe account which can't be done by someone without access, and I'm very uncomfortable handing out access unnecessarily.

**Comment by claytonflesher** [comment]
FYI, you guys lost $40 from me this year because this integration didn't exist. I imagine I'm not the only one.

**Comment by claytonflesher** [comment]
It looks like you guys don't actually need an integration for this. Here's a link to the docs.

https://stripe.com/docs/receipts#failed-payment-alerts

**Comment by carmalou** [comment]
Thanks Clayton!

**Comment by vlucas** [comment]
This would be nice and easy to implement, but I am not sure we have a direct link for someone to update or manage their subscription? @jagthedrummer?

**Comment by claytonflesher** [comment]
Has there been any update on this? Who has access to your Stripe subscription settings?

**Comment by kacollins** [comment]
I was able to do this.
