### ISSUE TITLE
Slack signup page isn't https

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#92]
Brendan Hill noted in Slack that http://slack.techlahoma.org/ isn't https.

Committee: Website and Social Media
Slack: [#techlahoma-website](https://techlahoma.slack.com/messages/techlahoma-website)

**Comment by bshambaugh** [comment]
https://letsencrypt.org/ ??

**Comment by DevinClark** [comment]
It's there. It just doesn't redirect to https. Heroku does not do this automatically.

**Comment by kacollins** [comment]
I'll let Brendan know. Can we close this one?

**Comment by brendan-hill** [comment]
I don't yet agree this should be closed because I don't understand enough from Devin's comment to see how encryption is there (my parsing of "It's there.") if https isn't showing in the browser. Doesn't have any unencrypted step in transmitting data render the whole thing effectively unsecured?

**Comment by DevinClark** [comment]
https://slack.techlahoma.org/ works and has a valid certificate. 
Heroku does not automatically redirect from http to https.

**Comment by brendan-hill** [comment]
Okay, I see. Unless there's a way to make Heroku direct [slack.techlahoma.org](url) (what most people will type) to [https://slack.techlahoma.org/](url) then there's nothing more to be done. If that's the case, I join the consensus already in progress.

**Comment by brendan-hill** [comment]
Is this anything though? My server-side / back-end config knowledge is limited.
https://medium.com/@seunghunsunmoonlee/how-to-enforce-https-redirect-http-to-https-on-heroku-deployed-apps-a87a653ba61e

**Comment by DevinClark** [comment]
We are using the slackin cli to run the app. https://github.com/rauchg/slackin
