### ISSUE TITLE
Typos on Get Involved Page

### ISSUE THREAD

**Issue by kacollins** [techlahoma/help-wanted#95]
Typos on https://www.techlahoma.org/get-involved:
Whether `your` make a small, one-time donation or sponsor an event, your gift supports `the our` statewide educational initiatives. Any donations you give to the Techlahoma 501(c)3 are tax deductible

Committee: Website and Social Media
Slack: [#techlahoma-website](https://techlahoma.slack.com/messages/techlahoma-website)

**Comment by BlakeGerard** [comment]
VOLUNTEER
`There's` no requirements to start volunteering!

**Comment by stephaniepurvis** [comment]
How do I volunteer to do this?

**Comment by kacollins** [comment]
You'll need access to edit the Techlahoma website. @DevinClark can you please give that to Stephanie?

**Comment by stephaniepurvis** [comment]
I volunteer as tribute! ;)

**Comment by DevinClark** [comment]
Sent Stephanie an invite.

**Comment by kacollins** [comment]
Thanks, y'all! @stephaniepurvis while you're at it, you might also look at #96 :)

**Comment by JeffLowe** [comment]
Oh man, I'm so sorry.  I was just in SquareSpace reviewing the site and just made these changes.  I'm closing this one out as complete, but @stephaniepurvis any other page updates are fair game for you!  Thank you.

**Comment by stephaniepurvis** [comment]
No problem! I was about to say it looks like it's been done! I can work on some of the other tasks.

**Comment by kacollins** [comment]
I believe that commenting on an issue before you start working on it is a best practice :)

**Comment by JeffLowe** [comment]
Yeah, I found this todo literally 30 seconds after I made the change to the site.  Totally agree best practice is to claim the task before doing.
